version: '2.2'
services:
  database:
    image: 'postgres:11.5-alpine'
    environment:
      - POSTGRES_DB=waprojectBaseHugoApi
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123mudar
    # volumes:
    #   - ./.data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    ports:
      - '4000:3000'
    depends_on:
      - database